[package]
name = "lapack"
version = "0.4.1"
authors = [
  "Andrew Straw <strawman@astraw.com>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
license = "MIT"
repository = "https://github.com/stainless-steel/lapack"
homepage = "https://github.com/stainless-steel/lapack"
documentation = "https://stainless-steel.github.io/lapack"
description = "The package provides an interface to the Linear Algebra PACKage."

[features]
default = ["openblas"]
openblas = ["lapack-sys/openblas"]
netlib = ["lapack-sys/netlib"]

[dependencies]
complex = "0.7"
libc = "*"

[dependencies.lapack-sys]
version = "0.3"
default-features = false
