[package]
name = "lapack"
version = "0.13.1"
license = "Apache-2.0/MIT"
authors = [
    "Andrew Straw <strawman@astraw.com>",
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides an interface to the Linear Algebra PACKage."
documentation = "https://docs.rs/lapack"
homepage = "https://github.com/stainless-steel/lapack"
repository = "https://github.com/stainless-steel/lapack"
categories = ["api-bindings", "science"]
keywords = ["linear-algebra"]
exclude = ["bin/*"]

[features]
default = ["openblas"]

accelerate = ["lapack-sys/accelerate"]
netlib = ["lapack-sys/netlib"]
openblas = ["lapack-sys/openblas"]

[dependencies]
libc = "0.2"

[dependencies.num-complex]
version = "0.1"
default-features = false

[dependencies.lapack-sys]
version = "0.11"
default-features = false
